### ISSUE TITLE
vim-illuminate does not work when colorscheme changes

### ISSUE THREAD

**Issue by froggenbit** [Cluas/nvim#2]
when i use colorscheme dark plus ,vim-illuminate works well.
but when i change colorscheme to others(for example , vscode)in lua/user/colorscheme.lua,vim-illuminate can't work.
<img width="246" alt="image" src="https://github.com/Cluas/nvim/assets/134925663/fdd139b1-f6ea-42f6-8d55-c1c01bd0b887">

<img width="325" alt="image" src="https://github.com/Cluas/nvim/assets/134925663/d35534ec-dfe9-4635-bb8b-b2580b580266">

when i use light colorscheme, i even can't see the underline.
<img width="269" alt="image" src="https://github.com/Cluas/nvim/assets/134925663/b0be2349-1cda-4972-a3c6-915b5ddd01b9">

i want to use some light background color scheme, what should i do?
hoping for reply

**Comment by Cluas** [comment]
You can change the highlight group used by vim-illuminate. This can be done by adding the following to your vim configuration:

```vim
augroup illuminate_augroup
    autocmd!
    autocmd VimEnter * hi link illuminatedWord YourHighlightGroup
augroup
```
Replace YourHighlightGroup with the name of a highlight group that is visible in your colorscheme.
